In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [2]:
data_kelompok14=pd.read_excel('./data_train4.xlsx')
pd.set_option('display.max_row', None)
display(data_kelompok14)

IQ   Sikap Kerja  Kecerdasan  Stabilitas Emosi    IP  Target
0     85            0           1                 2  2.53       0
1    100            1           2                 2  3.25       0
2     90            3           1                 2  2.80       0
3     86            1           1                 2  2.75       0
4     92            1           1                 1  2.50       0
5     98            2           2                 2  2.85       0
6     85            0           1                 2  2.18       0
7     91            2           1                 2  2.53       0
8     94            2           1                 2  2.25       0
9    100            1           2                 2  3.05       0
10   118            2           3                 1  2.90       0
11    88            2           1                 1  2.35       0
12    98            2           2                 2  3.13       0
13    95            2           1                 1  2.78       0
14    96            2           1                 2  2.93       0
15   104            2           2                 2  3.10       0
16    98            2           2                 2  3.23       0
17   105            3           2                 2  3.08       0
18    92            2           1                 2  3.28       0
19    90            2           1                 2  3.08       0
20    80            0           1                 1  1.25       0
21    86            1           1                 1  2.63       0
22    96            2           1                 2  2.83       0
23   100            2           2                 2  2.88       0
24    96            1           1                 1  3.33       0
25    99            2           2                 1  3.03       0
26   101            2           2                 1  3.20       0
27    98            2           2                 2  2.80       0
28    96            1           1                 2  2.88       0
29   110            2           3                 2  3.00       0
30    82            1           1                 2  2.53       0
31    90            2           1                 2  3.13       0
32   103            4           2                 2  2.88       0
33   105            2           2                 2  3.13       0
34    98            2           2                 2  2.98       0
35   124            2           4                 2  3.58       0
36   104            2           2                 2  3.13       0
37    99            2           2                 2  2.80       0
38    98            0           2                 2  2.70       0
39   100            2           2                 2  2.83       0
40   100            2           2                 2  2.80       0
41    93            2           1                 2  2.50       0
42    96            2           1                 2  3.10       0
43    90            0           1                 2  2.05       0
44   103            0           2                 2  2.98       0
45   100            3           2                 2  3.40       0
46   110            2           3                 2  3.38       0
47   100            2           2                 2  2.63       0
48    99            2           2                 2  3.20       0
49    91            3           1                 2  2.75       0
50   100            3           2                 2  3.50       0
51    85            2           1                 1  2.45       0
52   100            3           2                 2  2.83       0
53   105            2           2                 2  3.05       0
54    86            2           1                 2  1.88       0
55    96            1           1                 1  2.28       0
56    99            2           2                 2  2.95       0
57   102            4           2                 2  2.95       0
58   115            2           3                 2  2.70       0
59   100            2           2            

In [3]:
data_kelompok14.nunique()

IQ                   45
Sikap Kerja           5
Kecerdasan            5
Stabilitas Emosi      3
IP                  140
Target                2
dtype: int64

In [4]:
data_kelompok14.dtypes

IQ                    int64
Sikap Kerja           int64
Kecerdasan            int64
Stabilitas Emosi      int64
IP                  float64
Target                int64
dtype: object

In [5]:
data_kelompok14.isnull().sum()

IQ                  0
Sikap Kerja         0
Kecerdasan          0
Stabilitas Emosi    0
IP                  0
Target              0
dtype: int64

In [6]:
duplicated = data_kelompok14[data_kelompok14.duplicated(keep=False)]
duplicated.head()

Empty DataFrame
Columns: [IQ , Sikap Kerja, Kecerdasan, Stabilitas Emosi, IP, Target]
Index: []

In [7]:
duplicated = data_kelompok14.duplicated().sum()
if duplicated:
    print('Duplicates Row in Dataset are : {}'.format(duplicated))
else:
        print('Dataset contains no Duplicate values')

Dataset contains no Duplicate values


In [8]:
data_kelompok14.drop_duplicates(keep='first', inplace=True)

In [9]:
data_kelompok14

IQ   Sikap Kerja  Kecerdasan  Stabilitas Emosi    IP  Target
0     85            0           1                 2  2.53       0
1    100            1           2                 2  3.25       0
2     90            3           1                 2  2.80       0
3     86            1           1                 2  2.75       0
4     92            1           1                 1  2.50       0
5     98            2           2                 2  2.85       0
6     85            0           1                 2  2.18       0
7     91            2           1                 2  2.53       0
8     94            2           1                 2  2.25       0
9    100            1           2                 2  3.05       0
10   118            2           3                 1  2.90       0
11    88            2           1                 1  2.35       0
12    98            2           2                 2  3.13       0
13    95            2           1                 1  2.78       0
14    96            2           1                 2  2.93       0
15   104            2           2                 2  3.10       0
16    98            2           2                 2  3.23       0
17   105            3           2                 2  3.08       0
18    92            2           1                 2  3.28       0
19    90            2           1                 2  3.08       0
20    80            0           1                 1  1.25       0
21    86            1           1                 1  2.63       0
22    96            2           1                 2  2.83       0
23   100            2           2                 2  2.88       0
24    96            1           1                 1  3.33       0
25    99            2           2                 1  3.03       0
26   101            2           2                 1  3.20       0
27    98            2           2                 2  2.80       0
28    96            1           1                 2  2.88       0
29   110            2           3                 2  3.00       0
30    82            1           1                 2  2.53       0
31    90            2           1                 2  3.13       0
32   103            4           2                 2  2.88       0
33   105            2           2                 2  3.13       0
34    98            2           2                 2  2.98       0
35   124            2           4                 2  3.58       0
36   104            2           2                 2  3.13       0
37    99            2           2                 2  2.80       0
38    98            0           2                 2  2.70       0
39   100            2           2                 2  2.83       0
40   100            2           2                 2  2.80       0
41    93            2           1                 2  2.50       0
42    96            2           1                 2  3.10       0
43    90            0           1                 2  2.05       0
44   103            0           2                 2  2.98       0
45   100            3           2                 2  3.40       0
46   110            2           3                 2  3.38       0
47   100            2           2                 2  2.63       0
48    99            2           2                 2  3.20       0
49    91            3           1                 2  2.75       0
50   100            3           2                 2  3.50       0
51    85            2           1                 1  2.45       0
52   100            3           2                 2  2.83       0
53   105            2           2                 2  3.05       0
54    86            2           1                 2  1.88       0
55    96            1           1                 1  2.28       0
56    99            2           2                 2  2.95       0
57   102            4           2                 2  2.95       0
58   115            2           3                 2  2.70       0
59   100            2           2            

In [10]:
x_train=data_kelompok14.values
x_train=np.delete(x_train,5,axis=1)
y_train=data_kelompok14['Target'].values

In [11]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [12]:
x_train

array([[ 85.  ,   0.  ,   1.  ,   2.  ,   2.53],
       [100.  ,   1.  ,   2.  ,   2.  ,   3.25],
       [ 90.  ,   3.  ,   1.  ,   2.  ,   2.8 ],
       ...,
       [103.  ,   1.  ,   2.  ,   2.  ,   2.7 ],
       [ 98.  ,   2.  ,   2.  ,   2.  ,   2.4 ],
       [ 98.  ,   1.  ,   2.  ,   2.  ,   2.85]])

In [13]:
modelnb.fit(x_train,y_train)

GaussianNB()

In [14]:
data_test=pd.read_excel('./data_test4.xlsx')
display(data_test)

IQ   Sikap Kerja  Kecerdasan  Stabilitas Emosi    IP  Target
0     98            2           2                 1  3.60       0
1     94            0           1                 1  1.95       0
2     86            2           1                 2  2.98       0
3     86            2           1                 2  2.38       0
4     88            2           1                 1  2.55       0
5     98            0           2                 1  2.50       0
6    105            0           2                 1  3.33       0
7     94            2           1                 1  2.55       0
8    104            1           2                 1  2.90       0
9    104            2           2                 2  2.98       0
10    86            1           1                 1  2.13       0
11    96            2           1                 2  2.55       0
12    89            2           1                 2  2.63       0
13   105            2           2                 2  2.83       0
14    87            2           1                 2  2.68       0
15    96            3           1                 2  3.00       0
16    96            2           1                 2  2.89       0
17   104            1           2                 2  2.28       1
18   103            1           2                 2  2.39       0
19   105            2           2                 2  3.06       0
20   112            2           3                 2  2.72       0
21    99            2           2                 2  2.83       0
22   100            2           2                 1  2.11       1
23    80            2           1                 2  2.44       0
24   115            2           3                 1  3.06       0
25   107            2           2                 1  2.83       0
26    89            2           1                 2  2.28       1
27    84            2           1                 2  2.39       0
28   100            2           2                 2  3.50       0
29   100            2           2                 2  2.56       0
30    96            3           1                 2  2.50       0
31    87            2           1                 2  1.94       0
32   128            2           4                 2  2.67       0
33   104            3           2                 2  2.67       1
34   127            2           4                 2  2.33       0
35    82            3           1                 2  2.14       0
36    97            0           1                 2  2.71       0
37   102            1           2                 2  2.67       0
38   100            1           2                 1  2.64       0
39   104            3           2                 2  3.00       0
40    91            0           1                 2  1.67       0
41    90            2           1                 2  2.28       1
42   116            4           3                 2  2.61       0
43    91            2           1                 2  2.00       0
44   120            4           4                 2  2.22       0
45    99            2           2                 2  2.11       1
46    98            1           2                 2  1.94       0
47   101            2           2                 2  2.06       0
48   109            2           3                 2  2.89       0
49    86            3           1                 2  2.50       0
50   116            2           3                 2  3.61       0
51    99            2           2                 1  2.50       0
52   113            4           3                 2  2.72       0
53    98            0           2                 1  1.17       0
54    90            2           1                 2  1.78       0
55    92            1           1                 1  1.67       0
56   107            2           2                 1  2.95       0
57   115            3           3                 2  2.40       0
58    99            2           2                 2  3.00       0
59    96            2           1            

In [15]:
x_test=data_test.values
x_test=np.delete(x_test,5,axis=1)
y_test=data_test['Target'].values

In [16]:
y_pred_prob=modelnb.predict_proba(x_test)
y_pred_prob

array([[7.41674811e-01, 2.58325189e-01],
       [7.06913573e-01, 2.93086427e-01],
       [6.48222937e-01, 3.51777063e-01],
       [6.14085595e-01, 3.85914405e-01],
       [6.43143846e-01, 3.56856154e-01],
       [4.94149006e-01, 5.05850994e-01],
       [6.58088293e-01, 3.41911707e-01],
       [5.35520950e-01, 4.64479050e-01],
       [4.89473783e-01, 5.10526217e-01],
       [3.82594874e-01, 6.17405126e-01],
       [7.65490297e-01, 2.34509703e-01],
       [4.17867249e-01, 5.82132751e-01],
       [5.29836405e-01, 4.70163595e-01],
       [3.58036147e-01, 6.41963853e-01],
       [5.78888758e-01, 4.21111242e-01],
       [4.31941005e-01, 5.68058995e-01],
       [4.46764743e-01, 5.53235257e-01],
       [3.93909584e-01, 6.06090416e-01],
       [3.74916022e-01, 6.25083978e-01],
       [4.07961558e-01, 5.92038442e-01],
       [3.87602004e-01, 6.12397996e-01],
       [3.57608745e-01, 6.42391255e-01],
       [4.96493978e-01, 5.03506022e-01],
       [7.70452985e-01, 2.29547015e-01],
       [6.040457

In [17]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [18]:
prediksi = modelnb.predict(x_test)
prediksi

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediksi)

array([[39, 41],
       [24, 74]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, prediksi))

              precision    recall  f1-score   support

           0       0.62      0.49      0.55        80
           1       0.64      0.76      0.69        98

    accuracy                           0.63       178
   macro avg       0.63      0.62      0.62       178
weighted avg       0.63      0.63      0.63       178



In [25]:
# test manual
test = [[100,,4,2,2.89]]
predicted= modelnb.predict(test)
print("hasil prediksi :"),predicted

hasil prediksi :


(None, array([1], dtype=int64))

In [22]:
predicted_proba=modelnb.predict_proba(test)
print("hasil probabilitas:"),predicted_proba

hasil probabilitas:


(None, array([[0.25567482, 0.74432518]]))

In [24]:
import pickle
pickle.dump(modelnb, open("modelnb.pkl","wb"))