In [1]:
import pandas as pd
from IPython.display import display
import numpy as np

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

In [2]:
data_kelompok14=pd.read_excel('Dataset_14_Percobaan4.xlsx') 
data_kelompok14

IQ   Sikap Kerja  Kecerdasan  Stabilitas Emosi    IP  Target
0     85            0           1                 2  2.53       0
1     98            2           2                 1  3.60       0
2    100            1           2                 2  3.25       0
3     90            3           1                 2  2.80       0
4     86            1           1                 2  2.75       0
..   ...          ...         ...               ...   ...     ...
931   98            2           2                 2  2.45       1
932  103            1           2                 2  2.70       1
933   98            2           2                 2  2.40       0
934   98            1           2                 2  2.85       1
935   91            4           1                 2  2.90       1

[936 rows x 6 columns]

In [3]:
data_kelompok14.nunique()

IQ                   46
Sikap Kerja           5
Kecerdasan            5
Stabilitas Emosi      3
IP                  148
Target                2
dtype: int64

In [4]:
data_kelompok14.isnull().sum()

IQ                  0
Sikap Kerja         0
Kecerdasan          0
Stabilitas Emosi    0
IP                  0
Target              0
dtype: int64

In [5]:
duplicated = data_kelompok14[data_kelompok14.duplicated(keep=False)]
duplicated

IQ   Sikap Kerja  Kecerdasan  Stabilitas Emosi    IP  Target
30   100            2           2                 2  2.88       0
34    98            2           2                 2  2.80       0
50    93            2           1                 2  2.50       0
62    96            2           1                 2  2.55       0
65   105            2           2                 2  3.05       0
..   ...          ...         ...               ...   ...     ...
792  101            3           2                 2  2.85       1
823   95            2           2                 2  2.06       1
835   95            2           2                 2  2.06       1
841  100            2           2                 2  2.68       1
931   98            2           2                 2  2.45       1

[92 rows x 6 columns]

In [6]:
data_kelompok14.drop_duplicates(keep='first', inplace=True)

In [7]:
duplicated = data_kelompok14.duplicated().sum()
if duplicated:
    print('Duplicates Row in Dataset are : {}'.format(duplicated))
else:
       print('Dataset contains no Duplicate values')

Dataset contains no Duplicate values


In [8]:
data_kelompok14.info()
data_kelompok14.to_excel('Dataset_14_percobaan2.xlsx')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 935
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   IQ                889 non-null    int64  
 1   Sikap Kerja       889 non-null    int64  
 2   Kecerdasan        889 non-null    int64  
 3   Stabilitas Emosi  889 non-null    int64  
 4   IP                889 non-null    float64
 5   Target            889 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 48.6 KB


In [9]:
x=data_kelompok14.values
x=np.delete(x,5,axis=1)
y=data_kelompok14['Target'].values

In [10]:
x

array([[ 85.  ,   0.  ,   1.  ,   2.  ,   2.53],
       [ 98.  ,   2.  ,   2.  ,   1.  ,   3.6 ],
       [100.  ,   1.  ,   2.  ,   2.  ,   3.25],
       ...,
       [ 98.  ,   2.  ,   2.  ,   2.  ,   2.4 ],
       [ 98.  ,   1.  ,   2.  ,   2.  ,   2.85],
       [ 91.  ,   4.  ,   1.  ,   2.  ,   2.9 ]])

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [13]:
def get_score(modelnb,X_train, X_test, y_train, y_test):
    modelnb.fit(X_train,y_train)
    return modelnb.score(X_test,y_test)

In [14]:
kf=KFold(n_splits=5, random_state=123, shuffle=True)
print(kf)
scores_nb = []
i=1
for train_index, test_index in kf.split(x,y):
    print("Fold ", i)
    print("TRAIN :", train_index, "TEST :", test_index)
    X_train=x[train_index]
    X_test=x[test_index]
    y_train=y[train_index]
    y_test=y[test_index]
    i+=1
    scores_nb.append(get_score(GaussianNB(), X_train, X_test, y_train, y_test))
    print ("Train set:",X_train.shape, y_train.shape)
    print ("Test set:",X_test.shape, y_test.shape)

KFold(n_splits=5, random_state=123, shuffle=True)
Fold  1
TRAIN : [  0   1   2   3   6   7   8   9  10  12  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  32  33  34  37  38  39  40  42  43
  44  45  46  47  49  50  51  53  56  58  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  76  77  79  80  81  82  83  84  85  86  87  88
  89  92  93  94  95  96  97  98  99 101 102 104 105 106 107 108 109 110
 111 112 113 114 115 116 118 119 120 121 122 123 124 125 126 127 128 129
 130 132 133 135 136 137 139 140 141 142 143 144 146 148 149 150 152 153
 154 155 156 157 158 159 160 163 165 166 168 169 173 174 175 176 178 179
 180 181 183 184 186 187 189 190 191 192 193 194 197 198 199 201 202 203
 204 205 206 207 208 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 228 230 231 232 233 234 235 238 241 242 243 244 245 246 247
 248 250 251 252 253 254 255 256 257 258 259 260 262 263 264 265 267 268
 271 275 276 277 278 279 281 282 283 284 286 287 288 289 2

In [15]:
print("akurasi per fold :")
scores_nb

akurasi per fold :


[0.5730337078651685,
 0.5561797752808989,
 0.5561797752808989,
 0.6292134831460674,
 0.5310734463276836]

In [16]:
X_test

array([[1.00e+02, 1.00e+00, 2.00e+00, 2.00e+00, 3.25e+00],
       [9.00e+01, 3.00e+00, 1.00e+00, 2.00e+00, 2.80e+00],
       [8.50e+01, 0.00e+00, 1.00e+00, 2.00e+00, 2.18e+00],
       [1.18e+02, 2.00e+00, 3.00e+00, 1.00e+00, 2.90e+00],
       [9.80e+01, 2.00e+00, 2.00e+00, 2.00e+00, 3.13e+00],
       [9.50e+01, 2.00e+00, 1.00e+00, 1.00e+00, 2.78e+00],
       [9.00e+01, 2.00e+00, 1.00e+00, 2.00e+00, 3.13e+00],
       [9.90e+01, 2.00e+00, 2.00e+00, 2.00e+00, 2.80e+00],
       [9.80e+01, 0.00e+00, 2.00e+00, 2.00e+00, 2.70e+00],
       [9.60e+01, 2.00e+00, 1.00e+00, 2.00e+00, 3.10e+00],
       [1.10e+02, 2.00e+00, 3.00e+00, 2.00e+00, 3.38e+00],
       [9.90e+01, 2.00e+00, 2.00e+00, 2.00e+00, 3.20e+00],
       [1.00e+02, 3.00e+00, 2.00e+00, 2.00e+00, 3.50e+00],
       [1.05e+02, 2.00e+00, 2.00e+00, 2.00e+00, 3.05e+00],
       [9.60e+01, 1.00e+00, 1.00e+00, 1.00e+00, 2.28e+00],
       [9.90e+01, 2.00e+00, 2.00e+00, 2.00e+00, 2.95e+00],
       [8.60e+01, 2.00e+00, 1.00e+00, 2.00e+00, 2.83e+00

In [17]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1], dtype=int64)

In [18]:
modelnb.fit(X_train,y_train)

GaussianNB()

In [19]:
modelnb.predict_proba(X_test)

array([[4.30824428e-01, 5.69175572e-01],
       [4.04809317e-01, 5.95190683e-01],
       [7.20515798e-01, 2.79484202e-01],
       [8.75045932e-01, 1.24954068e-01],
       [3.49923294e-01, 6.50076706e-01],
       [8.20211019e-01, 1.79788981e-01],
       [5.25716988e-01, 4.74283012e-01],
       [2.79863010e-01, 7.20136990e-01],
       [3.72211402e-01, 6.27788598e-01],
       [4.19006950e-01, 5.80993050e-01],
       [4.61222785e-01, 5.38777215e-01],
       [3.66869793e-01, 6.33130207e-01],
       [4.53918102e-01, 5.46081898e-01],
       [3.21539740e-01, 6.78460260e-01],
       [8.55475723e-01, 1.44524277e-01],
       [3.00859431e-01, 6.99140569e-01],
       [5.55508186e-01, 4.44491814e-01],
       [3.11154698e-01, 6.88845302e-01],
       [3.03548981e-01, 6.96451019e-01],
       [5.46246635e-01, 4.53753365e-01],
       [3.22693031e-01, 6.77306969e-01],
       [4.00750669e-01, 5.99249331e-01],
       [8.10606240e-01, 1.89393760e-01],
       [3.71303656e-01, 6.28696344e-01],
       [6.489241

In [20]:
prediksi = modelnb.predict(X_test)
prediksi

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1], dtype=int64)

In [21]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediksi)

array([[36, 53],
       [30, 58]], dtype=int64)

In [22]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test, prediksi))

              precision    recall  f1-score   support

           0       0.55      0.40      0.46        89
           1       0.52      0.66      0.58        88

    accuracy                           0.53       177
   macro avg       0.53      0.53      0.52       177
weighted avg       0.53      0.53      0.52       177



In [23]:
# test manual
test = [[104,4,4,2,2.89]]
predicted= modelnb.predict(test)
print("hasil prediksi :"),predicted

hasil prediksi :


(None, array([1], dtype=int64))

In [24]:
predicted_proba=modelnb.predict_proba(test)
print("hasil probabilitas:"),predicted_proba

hasil probabilitas:


(None, array([[0.20531721, 0.79468279]]))

In [25]:
# serializing our model to a file called model.pkl
# import pickle
# pickle.dump(modelnb, open("modelnb.pkl","wb"))